### ISSUE TITLE
Enhancement request: need ability to get space on arbitrary file systems

### ISSUE THREAD

**Issue by fovea1959** [mongoose-os-libs/vfs-common#3]
Can someone pull one of the outstanding pull requests to provide this functionality?

**Comment by rojer** [comment]
reviewed, please address comments and it's good to go.

**Comment by fovea1959** [comment]
where are the comments to be addressed?

**Comment by rojer** [comment]
@fovea1959 sorry, forgot to push the button to publish comments. you should see them on the PR now.

**Comment by fovea1959** [comment]
thanks. 

I think if you use pull request #1 instead of pull request #2, it will have the changes as you requested. (I don't know why request #2 was put in place after #1 was done!)

**Comment by rojer** [comment]
yes, indeed. ok, but please use function names as suggested in my comments on #2

**Comment by fovea1959** [comment]
got it. reworking. Do we need to put prototypes into mgos_system.h?

**Comment by fovea1959** [comment]
fovea1959:vfs-free-space has commits with desired changes, should be good to go.

**Comment by rojer** [comment]
mgos_system.h should be updated with deprecation notice. i'll take care of it.
